---
title: "Untitled"
output: html_document
date: "2025-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
n1 <- rnorm(1000,0,1); head(20,1)
```

```{r}
n2 <- rnorm(15000,0,1); head(20,1)
```

```{r}
n3 <- rnorm(30000,0,1); head(20,1)
```

```{r}
```

```{r}
n3 <- rnorm(30000,0,1); head(n3,1)
```

```{r}
par(mfrow = c(1,3))
plot(n1, col="blue",
main = "1000 VA N(0,1)",
xlab ="Num de VA",
ylab = "N(0,1)")

plot(n2, col="green",
main = "15000 VA N(0,1)",
xlab ="Num de VA",
ylab = "N(0,1)")

plot(n3, col="red",
main = "30000 VA N(0,1)",
xlab ="Num de VA",
ylab = "N(0,1)")
```
## Comparacion de histogramas
```{r}
par(mfrow = c(1,4))
hist(n1, main="Histograma 1000 VA N(0,1)",
     col="lightpink",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n2, main="Histograma 15000 VA N(0,1)",
     col="lightgreen",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n3, main="Histograma 30000 VA N(0,1)",
     col="lightblue",
     xlab="VA generadas",
     ylab="N(0,1)")
X <- seq(-1,1, length=100)
curve(dnorm(x, mean = 0, sd=100),
      from=-3, to=3, lwd=2, col="blue",
      main= "Grafica de la N(0,1)", xlab="x",ylab="f(x)")
```
 ## Comparacion de histogramas fr n1, n2, n3, n4,n5 y n6
```{r}
n4 <- rnorm(50000,0,1);
n5 <- rnorm(75000,0,1);
n6 <- rnorm(100000,0,1);
par(mfrow = c(2,3))
hist(n1, main="Histograma 1000 VA N(0,1)",
     col="orange",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n2, main="Histograma 15000 VA N(0,1)",
     col="brown",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n3, main="Histograma 30000 VA N(0,1)",
     col="purple",
     xlab="VA generadas",
     ylab="N(0,1)")

hist(n4, main="Histograma 50000 VA N(0,1)",
     col="pink",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n5, main="Histograma 75000 VA N(0,1)",
     col="green",
     xlab="VA generadas",
     ylab="N(0,1)")
hist(n6, main="Histograma 100000 VA N(0,1)",
     col="blue",
     xlab="VA generadas",
     ylab="N(0,1)")
```
## Grafica de normales N(-1,1)


```{r}
n1 <- rnorm(1000,-1,1);
n2 <- rnorm(15000,-1,1);
n3 <- rnorm(30000,-1,1);
n4 <- rnorm(50000,-1,1);
n5 <- rnorm(75000,-1,1);
n6 <- rnorm(100000,-1,1);
par(mfrow = c(2,3))
hist(n1, main="Histograma 1000 VA N(-1,1)",
     col="orange",
     xlab="VA generadas",
     ylab="N(-1,1)")
hist(n2, main="Histograma 15000 VA N(-1,1)",
     col="brown",
     xlab="VA generadas",
     ylab="N(-1,1)")
hist(n3, main="Histograma 30000 VA N(-1,1)",
     col="purple",
     xlab="VA generadas",
     ylab="N(-1,1)")

hist(n4, main="Histograma 50000 VA N(-1,1)",
     col="pink",
     xlab="VA generadas",
     ylab="N(-1,1)")
hist(n5, main="Histograma 75000 VA N(-1,1)",
     col="green",
     xlab="VA generadas",
     ylab="N(-1,1)")
hist(n6, main="Histograma 100000 VA N(-1,1)",
     col="blue",
     xlab="VA generadas",
     ylab="N(-1,1)")
```

## Grafica de Normales N(0,2)
```{r}
n1 <- rnorm(1000,0,2);
n2 <- rnorm(15000,0,2);
n3 <- rnorm(30000,0,2);
n4 <- rnorm(50000,0,2);
n5 <- rnorm(75000,0,2);
n6 <- rnorm(100000,0,2);
par(mfrow = c(2,3))
hist(n1, main="Histograma 1000 VA N(0,2)",
     col="orange",
     xlab="VA generadas",
     ylab="N(0,2)")
hist(n2, main="Histograma 15000 VA N(0,2)",
     col="brown",
     xlab="VA generadas",
     ylab="N(0,2)")
hist(n3, main="Histograma 30000 VA N(0,2)",
     col="purple",
     xlab="VA generadas",
     ylab="N(0,2)")

hist(n4, main="Histograma 50000 VA N(0,2)",
     col="pink",
     xlab="VA generadas",
     ylab="N(0,2)")
hist(n5, main="Histograma 75000 VA N(0,2)",
     col="green",
     xlab="VA generadas",
     ylab="N(0,2)")
hist(n6, main="Histograma 100000 VA N(0,2)",
     col="blue",
     xlab="VA generadas",
     ylab="N(0,2)")
```

##grafica de normales N(media,desvstd)"

```{r}
media <- 0
desvstd <- 2.5
n1 <- rnorm(1000,media,desvstd);
n2 <- rnorm(15000,media,desvstd);
n3 <- rnorm(30000,media,desvstd);
n4 <- rnorm(50000,media,desvstd);
n5 <- rnorm(75000,media,desvstd);
n6 <- rnorm(100000,media,desvstd);
mititulo <- paste0("Histograma de N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")
par(mfrow = c(2,3))
hist(n1, main=mititulo,
     col="orange",
     xlab="VA generadas",
     ylab=etiquetay)
hist(n2, main=mititulo,
     col="brown",
     xlab="VA generadas",
     ylab=etiquetay)
hist(n3, main=mititulo,
     col="purple",
     xlab="VA generadas",
     ylab=etiquetay)

hist(n4, main=mititulo,
     col="pink",
     xlab="VA generadas",
     ylab=etiquetay)
hist(n5, main=mititulo,
     col="green",
     xlab="VA generadas",
     ylab="N(0,2)")
hist(n6, main=mititulo,
     col="blue",
     xlab="VA generadas",
     ylab=etiquetay)
```